server:
    port: 8082
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: service-users
                  uri: lb://service-users
                  predicates:
                      - Path=/api/v1/users/**
                - id: service-products
                  uri: lb://service-products
                  predicates:
                      - Path=/api/v1/products/**
